### ISSUE TITLE
Fetch error

### ISSUE THREAD

**Issue by oddsfinder** [DariusLukasukas/stocks#1]
Nice project but when running it I'm getting User
New crumb: yRG6Yj2wkbt
 ⨯ node_modules\yahoo-finance2\dist\esm\src\lib\yahooFinanceFetch.js (103:0) @ Object.yahooFinanceFetch [as _fetch]
 ⨯ Internal error: Error: Invalid Crumb. For Developers - https://bit.ly/yahoo-finance-api-feedback
 
 any idea why that occurs?

**Comment by DariusLukasukas** [comment]
Hey! :) Thank you for reporting this issue and for the detailed error message. Unfortunately, you've encountered a known problem with the unofficial Yahoo Finance API I'm using in the project. Yahoo has recently made changes that have broken compatibility with the node-yahoo-finance2 package.

Here's a breakdown of the situation:

- Yahoo Finance does not have an official public API. Projects like this rely on unofficial methods that are prone to changes.
- Recent Yahoo changes require a workaround. See this discussion for more details: https://github.com/gadicc/node-yahoo-finance2/issues/764
- Some users have shared temporary solutions in that thread. I haven't had a chance to confirm their effectiveness.

As of my plans, I understand this is frustrating, and I apologize for the inconvenience. I'm currently busy with other tasks but plan to investigate a fix sometime this week or next. In the meantime, please try the workarounds suggested in the GitHub issue thread.

**Important Note:** Please consider filling out Yahoo's feedback form:  https://bit.ly/yahoo-finance-api-feedback This helps signal your interest in an official API that could bring long-term stability.

Thank you again for your patience and understanding!

**Comment by DariusLukasukas** [comment]
Great news! The node-yahoo-finance2 package has released an update that fixes the "Invalid Crumb" error. Please update your project's dependencies to get the latest version of the package. This should resolve the issue you were experiencing.

Let me know if you have any further problems. :)

**Comment by DariusLukasukas** [comment]
Great news! The node-yahoo-finance2 package has released an update that fixes the "Invalid Crumb" error. Please update your project's dependencies to get the latest version of the package. This should resolve the issue you were experiencing.

Let me know if you have any further problems. :)
